# Now using version 1.2.0 on 2019-06-28

# Convert /* */ comments to // comments where possible
# this is nightly   normalize_comments = true

# Forces the where clause to be laid out on a single line.
# still unstable where_single_line = true

# if rustfmt sometimes cannot format nicely
# disable_all_formatting = true

# reorder_imports = false
# reorder_modules = false
# reorder_impl_items = false
# force_multiline_blocks = true
# type_punctuation_density = Wide
# space_before_type_annotation = true
# space_after_type_annotation_colon = true
# spaces_around_ranges = true